[Editor]
# Editor minimum width (>= 800)
Width = 800
# Editor minimum height (>= 600)
Height = 600
# Editor font-family, font-size, linespace.
FontFamily = "Ricty"
FontSize = 12
Linespace = 0
# neovim extend feature
ExtCmdline = true
ExtWildmenu = true
ExtPopupmenu = true
ExtTabline  = true
# Gonvim copy the yank text to clipboad
Clipboard = true
# Editor cursor blink
CursorBlink = false
# Disable IME in Normal mode
DisableImeInNormal = false
# load vimscript after setting of g:gonvim_running=1
GinitVim = '''
  	set guifont=Ricty:h14
'''
# start fullscreen
StartFullscreen = false

[Statusline]
Visible = true
# textLabel / icon / background / none
ModeIndicatorType = "icon"
# Color setting per vim-modes, if you want to change
NormalModeColor = "#3cabeb"
CommandModeColor = "#5285b8"
InsertModeColor = "#2abcb4"
ReplaceModeColor = "#ff8c0a"
VisualModeColor = "#9932cc"
TerminalModeColor = "#778899"
# Statusline component
# Left = [ "mode", "filepath", "filename" ]
# Right = [ "message", "git", "filetype", "fileformat", "fileencoding", "curpos", "lint" ]


[Tabline]
Visible = true

[Lint]
Visible = true

[ScrollBar]
Visible = true

[ActivityBar]
Visible = false
DropShadow = false

[MiniMap]
Visible = false

[SideBar]
Visible = false
DropShadow = false
Width = 300
AccentColor = "#5596ea"

[Workspace]
# name: directoryname
# full: /path/to/directoryname
# minimum: /p/t/directoryname
PathStyle = "minimum"
# Restore session-information that was ended without being saved
RestoreSession = false
# File open command in gonvim file explorer
FileExplorerOpenCmd = ":tabnew"
