ClassLength:
    Enabled: false

LineLength:
    Enabled: false

MethodLength:
    Enabled: false

CyclomaticComplexity:
    Enabled: false

Documentation:
    Enabled: false

Metrics/AbcSize:
    Max: 20
