[[mgr.prepend_keymap]]
on = [ "g", "n" ]
run = 'shell --block "nvim -d %s1 %s2"'
desc = "Diff selected files"

[[mgr.prepend_keymap]]
on = [ "g", "o" ]
run = 'open --interactive'
desc = "Open files with tools"

[[mgr.prepend_keymap]]
on = "<Up>"
run = "arrow 1"
desc = "Move down (reversed for bottom-aligned)"

[[mgr.prepend_keymap]]
on = "<Down>"
run = "arrow -1"
desc = "Move up (reversed for bottom-aligned)"

[[mgr.prepend_keymap]]
on = "k"
run = "arrow 1"
desc = "Move down (reversed for bottom-aligned)"

[[mgr.prepend_keymap]]
on = "j"
run = "arrow -1"
desc = "Move up (reversed for bottom-aligned)"

[[mgr.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "close yazi"

