[mgr]
show_hidden = true

[opener]
edit = [
	{ run = "$EDITOR $0", desc = "Edit", block = true, for = "unix" },
	{ run = "%EDITOR% %0", desc = "Edit", block = true, for = "windows" },
]

open = [
    { run = "xdg-open $1", desc = "Open", for = "unix" },
]

diff = [
    { run = "nvim -d $1 $2", desc = "diff", block = true },
]

test = [
    { run = "echo %s", block = true, desc = "Test" },
]

[open]
prepend_rules = [
    { mime = "text/*", use = ["edit", "open", "diff", "test"]}
]
