[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:dein#install_log_filename='$HOME/.cache/dein/install.log'
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
let g:vaffle_auto_cd = 1
let g:vaffle_show_hidden_files = 1
nnoremap <C-o> :<C-u>Vaffle<CR>
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
nnoremap <C-k> <Plug>(caw:hatpos:toggle)
vnoremap <C-k> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['iceberg.vim']
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'iceberg',
      \ 'active': {
      \    'left': [
      \      [ 'mode', 'paste' ],
      \      [ 'readonly', 'fugitive', 'filename', 'modified' ],
      \    ]
      \ },
      \ 'component': {
      \   'lineinfo': "\ue0a1".'%3l:%-2v',
      \ },
      \ 'component_function': {
      \    'readonly': 'LightlineReadonly',
      \    'fugitive': 'LightlineFugitive',
      \ },
      \ 'separator': {'left': "\ue0b0", 'right': "\ue0b2"},
      \ 'subseparator': {'left': "\ue0b1", 'right': "\ue0b3"},
      \ }
function! LightlineReadonly()
    return &readonly ? "\ue0a2" : ''
endfunction
function! LightlineFugitive()
    if exists('*fugitive#head')
        let branch = fugitive#head()
        return branch !=# '' ? "\ue0a0".branch : ''
    endif
    return ''
endfunction
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add ='''
set statusline+=%#warningmsg#
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
au FileType go nnoremap gr (go-run)
au FileType go nnoremap gt (go-test)
let g:go_hightlight_functions = 1
let g:go_hightlight_methods = 1
let g:go_hightlight_structs = 1
let g:go_hightlight_interfaces = 1
let g:go_hightlight_operators = 1
let g:go_hightlight_build_constraints = 1
let g:go_fmt_command = "goimports"
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
