[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neoyank.vim', 'neomru.vim']
hook_add = '''
nnoremap <silent> ;f :<C-u>Denite file_rec<CR>
nnoremap <silent> ;m :<C-u>Denite file_mru<CR>
nnoremap <silent> ;y :<C-u>Denite neoyank<CR>
nnoremap <silent> ;b :<C-u>Denite buffer<CR>
'''
hook_post_source = '''
call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
