[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['neco-vim', 'neco-syntax']
on_i = 1
hook_add = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#source#go#gocode_binary = '$HOME/go/bin/gocode'
let g:deoplete#auto_complete_delay = 0
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neoyank.vim', 'neomru.vim']
hook_add = '''
nnoremap <silent> ;f :<C-u>Denite file_rec<CR>
nnoremap <silent> ;m :<C-u>Denite file_mru<CR>
nnoremap <silent> ;y :<C-u>Denite neoyank<CR>
nnoremap <silent> ;b :<C-u>Denite buffer<CR>
nnoremap <silent> ;d :<C-u>Denite directory_mru<CR>
'''
hook_post_source = '''
call denite#custom#var('file_rec', 'command',
    \ ['ag', '--follow', '--nocolor', '--nogroup',
    \  '--hidden', '-g', ''])
call denite#custom#option('default', 'prompt', '>')
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')
call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/neco-vim'
