[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:dein#install_log_filename='$HOME/.cache/dein/install.log'
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
set background=dark
au MyAutoCmd VimEnter * nested colorscheme iceberg
'''

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
nnoremap <C-k> <Plug>(caw:hatpos:toggle)
vnoremap <C-k> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
au FileType go nnoremap gr (go-run)
au FileType go nnoremap gt (go-test)
let g:go_hightlight_functions = 1
let g:go_hightlight_methods = 1
let g:go_hightlight_structs = 1
let g:go_hightlight_interfaces = 1
let g:go_hightlight_operators = 1
let g:go_hightlight_build_constraints = 1
let g:go_fmt_command = "goimports"
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add ='''
set statusline+=%#warningmsg#
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'cohama/lexima.vim'
